export const groupCode = "GP01";
// use for Category
export const FETCH_COURSE_CATEGORY_REQUEST = "FETCH_COURSE_CATEGORY_REQUEST";
export const FETCH_COURSE_CATEGORY_SUCCESS = "FETCH_COURSE_CATEGORY_SUCCESS";
export const FETCH_COURSE_CATEGORY_FAILED = "FETCH_COURSE_CATEGORY_FAILED";
// use for Top-Course, fetch all courses
export const FETCH_COURSE_REQUEST = "FETCH_COURSE_REQUEST";
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS";
export const FETCH_COURSE_FAILED = "FETCH_COURSE_FAILED";